# Generated by Django 5.1 on 2024-08-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0005_notice_pointshop_delete_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointshop',
            name='shop',
            field=models.CharField(blank=True, null=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pointshop',
            name='stuff',
            field=models.CharField(unique=True, blank=True, null=True, max_length=255),
        ),
    ]
