# Generated by Django 4.2.7 on 2024-10-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0007_alter_pointshop_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='contents',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pointshop',
            name='shop',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pointshop',
            name='stuff',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
