# Generated by Django 4.2.7 on 2024-09-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostitem', '0004_alter_lost_category_alter_lost_getwhere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lost',
            name='title',
            field=models.CharField(blank=True, null=True, max_length=255),
        ),
    ]
