# Generated by Django 4.2.7 on 2024-10-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostitem', '0006_alter_lost_lostdate_alter_lost_losttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lost',
            name='moredesc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
